name: "test version reading"
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/read-version-node.yml"
      - ".github/workflows/read-version-node-test.yml"

jobs:
  invoke:
    uses: Devecorsoft/workflows/.github/workflows/read-version-node.yml@main
    with:
      package_json: "./test/package.json"
  assert:
    runs-on: ubuntu-latest
    needs:
      - invoke
    steps:
      - if: ${{ needs.invoke.outputs.version != '1.0.0' }}
        run: |
          echo "Failed: expect ${{ needs.invoke.outputs.version }} to be '1.0.0'"
          exit 1