name: github packages
on:
  workflow_call:
    inputs:
      package_json:
        description: "path to package.json"
        required: true
        type: string
    outputs:
      version:
        description: "current version in package.json"
        value: ${{ jobs.read_version_from_package_json.outputs.version }}

jobs:
  read_version_from_package_json:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_current_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Read current version
        id: read_current_version
        run: |
          mkdir -p .github/reusable/scripts
          echo "$(curl -s https://raw.githubusercontent.com/DevecorSoft/workflows/main/.github/scripts/read-version-node.js)" > .github/reusable/scripts/read-version-node.js
          cat .github/reusable/scripts/read-version-node.js
          echo "::set-output name=version::$(node .github/reusable/scripts/read-version-node.js ${{ inputs.package_json }})"
