name: "test version reading"
on:
  push:
    branches: [main]
    paths:
      - "publish/workflows/read_version.js"
      - ".github/workflows/read-version-test.yml"
      - ".github/workflows/read-version.yml"

jobs:
  invoke:
    uses: Devecorsoft/workflows/.github/workflows/verify-version.yml@main
    with:
      platform: "nodejs"
      path: "./test/package.json"
