name: "test version verification"
on:
  push:
    branches: [main]
    paths:
      - "publish/workflows/verify-version.js"
      - ".github/workflows/verify-version-test.yml"
      - ".github/workflows/verify-version.yml"

jobs:
  invoke:
    uses: Devecorsoft/workflows/.github/workflows/verify-version.yml@main
    with:
      current: "v1.0.6"
