name: "verify version bumped"
on:
  workflow_call:
    inputs:
      current:
        required: true
        type: string
      destination:
        required: false
        type: string
        default: "git-tag"
        

jobs: 
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - id: verify_step
        run: |
          mkdir -p .github/reusable/scripts
          echo "$(curl -s https://raw.githubusercontent.com/DevecorSoft/workflows/main/publish/verify_version.js)" > .github/reusable/scripts/verify-version.js
          node .github/reusable/scripts/verify-version.js --current=${{ inputs.current }} --destination=${{ inputs.destination }}
